# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadPipelineArtifact@2
  displayName: 'Download CloudFormation template'
  inputs:
    artifactName: 'nombre-del-artifact'
    downloadPath: '$(System.ArtifactsDirectory)/cloudformation'
    artifactDownloadPath: 'ClouFormation/CRUD_cloudfomration.yaml'

- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: 'awsConnection'
    regionName: 'us-east-2'
    stackName: 'CRUD'
    templateSource: 'linkedArtifact'
    linkedArtifactName: 'nombre-del-artifact'
    deploymentMode: 'incremental'
    actionIfStackAlreadyExists: 'update'
    templateFile: '$(System.ArtifactsDirectory)/cloudformation/CRUD_cloudfomration.yaml'


